QosManager: code to handle epg level qos configuration.
noironetworks/opflex pull request #226
Opened 2020-08-31 06:07 UTC by ansao-aci

2020-09-01 00:09 UTC, tomflynn commented on agent-ovs/lib/QosManager.cpp
> +            const unordered_set<string> &interfaces = itr->second;
could you refactor and move lines 387-393 into a method and call from 404-410 to reduce dup code

2020-09-01 00:10 UTC, tomflynn commented on agent-ovs/lib/QosManager.cpp
> +        auto itr = policyMap.find(uri);
Can you fix the indentation for the rest of the method?

2020-09-01 00:12 UTC, tomflynn commented on agent-ovs/lib/QosManager.cpp
> +		}
fix indent

2020-09-01 00:13 UTC, tomflynn commented on agent-ovs/lib/QosManager.cpp
> +			auto polIter = reqToPol.find(reqUri.get());
indentation of this block is off

2020-09-01 00:21 UTC, tomflynn commented on agent-ovs/lib/QosManager.cpp
> +            optional<URI> oldEgUri = boost::none;
Just declare this variable when you first use it to address the codacy complaint

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +            optional<URI> oldEgUri = boost::none;
Done

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +			auto polIter = reqToPol.find(reqUri.get());
Fixed.

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +		}
Done.

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +        auto itr = policyMap.find(uri);
Done.

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +            const unordered_set<string> &interfaces = itr->second;
Done.

2020-09-03 13:44 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +        LOG(DEBUG) << "update on QosUniverseListener URI " << uri ;
Done

2020-09-12 01:17 UTC, tomflynn requested changes

2020-09-15 09:48 UTC, ansao-aci commented on agent-ovs/lib/include/opflexagent/QosManager.h
> +        lock_guard<recursive_mutex> guard1(qos_mutex);
Changed the scope of qos_mutex to public so that non-member functions could acquire lock on qos_mutex  while reading from maps.

2020-09-15 18:03 UTC, tomflynn approved these changes

2020-09-15 18:03 UTC, merged