Optimize QosManager: increase concurrency.
noironetworks/opflex pull request #284
Opened 2020-10-15 16:25 UTC by ansao-aci

Modb notifications  are processed concurrently. Concurrent tasks are
1. updating cached information
2. programme ovsdb/flows to configure qos

2020-10-20 05:06 UTC, tomflynn requested changes
Just some minor comments

2020-10-22 06:34 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +        optional<shared_ptr<modelgbp::qos::Requirement>> qosReqOpt =
Done.

2020-10-22 06:34 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +            optional<URI> egressUri;
Done.

2020-10-22 06:34 UTC, ansao-aci commented on agent-ovs/lib/QosManager.cpp
> +        LOG(INFO) << "epgToReq, epg: : " <<epg
Done.

2020-10-22 19:39 UTC, tomflynn approved these changes

2020-10-22 19:39 UTC, merged