Delete Qos and queue entry from ovsdb.
noironetworks/opflex pull request #291
Opened 2020-10-21 09:54 UTC by ansao-aci

Unreferenced  QoS and Queue records are not automatically destroyed. This change set takes care of deleting existing  qos/queue entry before creating new records.
Reference: http://www.openvswitch.org//support/dist-docs/ovs-vsctl.8.txt

2020-10-23 18:19 UTC, tomflynn requested changes
Please enhance the UTs to cover the new code as well.

2020-10-23 18:19 UTC, tomflynn commented on agent-ovs/ovs/OvsdbConnection.cpp
> +                                        LOG(DEBUG) << "map key value = " << keyInt;
Can you remove the debug logs?

2020-10-23 18:19 UTC, tomflynn commented on agent-ovs/ovs/OvsdbConnection.cpp
>                                      LOG(WARNING) << "map key type = " << mapMemberItr->GetArray()[0].GetType();
Can you remove these two warn logs? The initial log was only there because we weren't handling the case yet

2020-10-23 18:19 UTC, tomflynn commented on agent-ovs/ovs/OvsdbConnection.cpp
> +                            LOG(DEBUG) << "qos uuid " << rowUuid;
Can you remove this debug since you're logging with UUID again below

2020-10-23 18:19 UTC, tomflynn commented on agent-ovs/ovs/include/OvsdbState.h
> +                 LOG(INFO) << "queue: " << it->first << "=" << it->second;
lower to DEBUG or remove
indentation is off for this block as well

2020-10-23 18:19 UTC, tomflynn commented on agent-ovs/ovs/include/OvsdbState.h
> +                    std::map<std::string, std::string>  col = row.second["qos"].getCollectionValue();
use auto& instead

2020-10-27 10:45 UTC, ansao-aci commented on agent-ovs/ovs/OvsdbConnection.cpp
> +                                        LOG(DEBUG) << "map key value = " << keyInt;
Done.

2020-10-27 10:47 UTC, ansao-aci commented on agent-ovs/ovs/include/OvsdbState.h
> +                    std::map<std::string, std::string>  col = row.second["qos"].getCollectionValue();
done.

2020-10-27 10:47 UTC, ansao-aci commented on agent-ovs/ovs/include/OvsdbState.h
> +                 LOG(INFO) << "queue: " << it->first << "=" << it->second;
done.

2020-10-27 10:47 UTC, ansao-aci commented on agent-ovs/ovs/OvsdbConnection.cpp
> +                            LOG(DEBUG) << "qos uuid " << rowUuid;
done.

2020-10-28 04:55 UTC, tomflynn approved these changes

2020-10-28 04:56 UTC, merged