minor Logaction changes on PolicyManager side
noironetworks/opflex pull request #292
Opened 2020-10-22 20:48 UTC by Bhavanaashok33

if we are able to resolve LogAction from the policyManager, that indicates that the agent is able to resolve the LogAction from the leaf(if it is set). we can just assign ruleLog=true and discard "ruleLog = resloveLog.get()->getLog(0) != 0 ;"

2020-10-22 22:37 UTC, tomflynn requested changes

2020-10-22 22:37 UTC, tomflynn commented on agent-ovs/lib/PolicyManager.cpp
> +	          for (const shared_ptr<L24Classifier>& c : classifiers) {
This indentation change doesn't seem like it's needed

2020-10-22 22:37 UTC, tomflynn commented on agent-ovs/lib/PolicyManager.cpp
> +                        optional<shared_ptr<LogAction> > resloveLog =
typo - resloveLog -> resolveLog

2020-10-22 22:37 UTC, tomflynn commented on agent-ovs/ovs/FlowUtils.cpp
> +       if (log != false) {
if (log) instead?

2020-10-22 22:37 UTC, tomflynn commented on agent-ovs/ovs/FlowUtils.cpp
> +                             if (log != false) {
if (log) instead?

2020-10-23 03:34 UTC, shastrinator commented on agent-ovs/ovs/FlowUtils.cpp
> +                             if (log != false) {
Original check was correct. log is an integer

2020-10-23 03:34 UTC, shastrinator commented on agent-ovs/lib/PolicyManager.cpp
> +                        ruleLog = true;
The check is correct. Can we fix the proxy code which causes these issues?

2020-10-23 04:33 UTC, tomflynn commented on agent-ovs/lib/PolicyManager.cpp
> +                        ruleLog = true;
Bhavana and I were chatting about this. The current leaf implementation creates a relation to GbpLogAction only if logging should be enabled. It does not set the log variable. It just doesn't create the relation at all if logging is not enabled

Waiting for a fix in the leaf implementation means we won't have an image for customers until 5.2 is released which will be a while. Alternatively, since we don't have another impl that uses this var, we can work with the current leaf impl and remove the log variable from GbpLogAction to make it clear. It doesn't really serve any purpose today as you can just avoid creating the relation if logging should be disabled

2020-10-23 16:54 UTC, shastrinator approved these changes

2020-10-23 18:06 UTC, tomflynn approved these changes

2020-10-23 18:07 UTC, merged