Enhancements to droplog - part 1
noironetworks/opflex pull request #410
Opened 2022-07-27 07:38 UTC by shastrinator

1. Print src and dst mac as separate fields
2. Separate log file for drop_logs.
   Configure droplog destination with command line arguments
   --drop_log_file <file-name> --drop_log_syslog (in case sink is
   syslog)
   By default droplogs go to the opflex-agent log file.

Signed-off-by: Kiran Shastri <shastrinator@gmail.com>

2022-11-23 17:52 UTC, mchalla approved these changes

2022-12-06 19:37 UTC, tbachman commented on agent-ovs/ovs/PacketDecoderLayers.cpp
> +    fmtStr = boost::format(" DMAC=%1% SMAC=%2% ETYP=%3%");
This is a nit, but can we switch the DMAC and SMAC order in the log? This would make the source/dest consistent with how the IPs get displayed (see expected unit test output below - like "DMAC=5a:08:66:ce:0b:49 SMAC=9e:72:a6:94:18:af ETYP=IPv4 SRC=14.0.0.2 DST=100.0.0.1" would be better as "SMAC=9e:72:a6:94:18:af DMAC=5a:08:66:ce:0b:49  ETYP=IPv4 SRC=14.0.0.2 DST=100.0.0.1".

2022-12-06 19:41 UTC, tbachman requested changes
A minor nit, for consistency.

2022-12-06 20:48 UTC, shastrinator commented on agent-ovs/ovs/PacketDecoderLayers.cpp
> +    fmtStr = boost::format(" DMAC=%1% SMAC=%2% ETYP=%3%");
Done thanks.

2023-01-18 17:32 UTC, tbachman approved these changes

2023-01-18 17:32 UTC, merged

2023-01-18 17:51 UTC, tbachman commented
Can you backport this to kmr2?

2023-01-18 18:02 UTC, shastrinator commented
Sure. will do.