Allow multiple switch names
noironetworks/opflex pull request #439
Opened 2023-05-22 23:59 UTC by sayalinaval

Allow multiple switch names to be passed from OVSRenderer to support multiple switches on NetFlowRenderer.

2023-05-23 21:12 UTC, christides11 approved these changes

2023-05-23 21:37 UTC, Bhavanaashok33 commented on agent-ovs/ovs/test/QosRenderer_test.cpp
can you add "br-fab" to the list of switches?

2023-05-23 21:38 UTC, Bhavanaashok33 commented on agent-ovs/ovs/test/SpanRenderer_test.cpp
can you add "br-fab" to the list of switches?

2023-05-25 20:46 UTC, sayalinaval commented on agent-ovs/ovs/test/QosRenderer_test.cpp
Yes, we can. But we are already testing that for NetFlowRenderer where we will pass a list of switch names (2) instead of just 1.

2023-05-26 17:42 UTC, Bhavanaashok33 approved these changes

2023-06-26 13:27 UTC, tbachman requested changes
In looking at this a bit more, I think we should go with a different approach. The NetFlowManager aggregates NetFlowListener objects when the NetFlowListener registers with the NetFlowManager. Each NetFlowRenderer is a NetFlowListener, so instead of a single NetFlowRenderer managing a list of switches, I think it should instead take a single switch. That means we need multiple NetFlowRenderer objects - one for each switch implementing NetFlow. This would also avoid changes to the other renderer classes, since there wouldn't need to be changes to the JsonRpcRenderer.

2023-06-29 11:41 UTC, tbachman requested changes
Needs a bit more work, but the right direction.

2023-06-29 11:41 UTC, tbachman commented on agent-ovs/ovs/OVSRenderer.cpp
> +    netflowRenderer.start(accessBridgeName, ovsdbConnection.get());
I think this is overwriting one switch with another. You'll need to create separate NetFlowRenderer members for the integration and access bridges.

2023-06-30 10:27 UTC, tbachman approved these changes

2023-06-30 10:39 UTC, merged

2023-06-30 10:39 UTC, tbachman commented
Thanks for the patch! Please backport to kmr2.