Stats collection for NAT traffic in openstack and exporting the packe…
noironetworks/opflex pull request #494
Opened 2024-01-31 23:03 UTC by Bhavanaashok33

…t count, byte count to promethues

2024-02-13 19:07 UTC, Bhavanaashok33 commented
> Please update Agent.cpp to exclude these stats from being reported to leaf (see framework.overrideObservableReporting calls)

okay got it

2024-02-14 19:16 UTC, mchalla requested changes
Overall looks fine to me. As I mentioned yesterday it would have been nice if you did a single hash map lookup to get both the toVM and fromVM entry, kind of how connection tracking is implemented, see conntrack -L. You can do it later if you have time.

Few comments inline.

2024-02-14 19:16 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_METRICS_MIN; metric <=  NAT_VM2EXT_MAX; metric = NAT_METRICS(metric+1)){
Is it possible to avoid these loops by creating the metrics via some trigger (when flow is added) At the very least you can merge this with the next loop below.

2024-02-14 19:16 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_EXT2VM_MIN; metric <= NAT_METRICS_MAX; metric = NAT_METRICS(metric+1)){
Same here. Merge the loops into single loop.

2024-02-14 19:16 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
> +
Do we need to check natStatsEnabled here and not do anything if its disabled ?

2024-02-14 19:55 UTC, Bhavanaashok33 commented on agent-ovs/ovs/IntFlowManager.cpp
> +
okay i can add a statement here to no to do anything at all if disabled

2024-02-14 19:57 UTC, Bhavanaashok33 commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_METRICS_MIN; metric <=  NAT_VM2EXT_MAX; metric = NAT_METRICS(metric+1)){
since I am doing hash map look up twice: ext to vm && vm to ext, these the looks also get executed twice for FromVm and ToVm. if i do one hash map look up for both egress and ingress, i can get ride of two loops and make it just one

2024-02-14 19:59 UTC, Bhavanaashok33 commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_EXT2VM_MIN; metric <= NAT_METRICS_MAX; metric = NAT_METRICS(metric+1)){
addressed already

2024-02-14 20:24 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_METRICS_MIN; metric <=  NAT_VM2EXT_MAX; metric = NAT_METRICS(metric+1)){
yea but you are executing the loop twice for egress and twice for ingress so total 4 times. One to check if the counter exists and another to update. You can check if counter exists right before the update in the second loop.

2024-02-14 20:55 UTC, Bhavanaashok33 commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +	for(NAT_METRICS metric=NAT_METRICS_MIN; metric <=  NAT_VM2EXT_MAX; metric = NAT_METRICS(metric+1)){
okay got it. will make the change

2024-02-15 15:11 UTC, tbachman requested changes

2024-02-15 15:11 UTC, tbachman commented on agent-ovs/ovs/OVSRenderer.cpp
> +    natStatsManager.stop();
should we conditionalize this for when it's enabled (similar to those above it)?

2024-02-15 22:14 UTC, Bhavanaashok33 commented on genie/MODEL/EXTENSIONS/GBP/extensions.mdl
> +        member[auuid; type=reference/UUID]
Right. EP counters doesnt have to be tied to agent uuid. i can just keep the epuuid and remove the agent uuid.

2024-02-15 22:17 UTC, Bhavanaashok33 commented on genie/MODEL/EXTENSIONS/GBP/extensions.mdl
> +    class[VmToExtStatsCounter;
Well, currently we support openstack NAT stats and i decided to keep it as VM to External. but i  can change the names to be more generic for both k8s and openstack

2024-02-15 22:17 UTC, Bhavanaashok33 commented on genie/MODEL/EXTENSIONS/GBP/extensions.mdl
> +            parent[class=observer/PolicyStatUniverse]
right.

2024-02-16 19:34 UTC, Bhavanaashok33 commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +    {
i missed the lock there. thanks for pointing it out :-)

2024-02-16 19:37 UTC, Bhavanaashok33 commented on agent-ovs/ovs/NatStatsManager.cpp
> +     }
will fix indentation

2024-02-16 19:38 UTC, Bhavanaashok33 commented on agent-ovs/ovs/OVSRenderer.cpp
> +    natStatsManager.stop();
yes. good catch

2024-02-16 19:42 UTC, Bhavanaashok33 commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +                return;
it is supposed to be break. changed it

2024-02-18 18:31 UTC, tbachman approved these changes

2024-02-18 18:36 UTC, mchalla requested changes
Pl fix the indentation in multiple places

2024-02-18 18:36 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
> +	    if(isNatStatsEnabled) {
indentation

2024-02-18 18:36 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
>                           .ipDst(floatingIp).reg(0, fepgVnid),
indentation

2024-02-18 18:36 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
> +	if(isNatStatsEnabled) {
indentation

2024-02-18 18:36 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
> +	    if(isNatStatsEnabled) {
indentation

2024-02-18 18:36 UTC, mchalla commented on agent-ovs/ovs/IntFlowManager.cpp
>                  .ethSrc(effNextHopMac).ipDst(floatingIp)
indentation

2024-02-20 16:14 UTC, mchalla approved these changes
few more indentation issues. i approved it nevertheless. pl fix those and we are good to go.

2024-02-20 16:14 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +            hgauge_pair_t hgauge = getDynamicGaugeNatCounter(metric, uuid);
This section has extra spaces. switch left.

2024-02-20 16:14 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +    }else if (dir == "ExtToEp") {
add space between } and else

2024-02-20 16:14 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +               return true;
shift left this line to align with the hash_new

2024-02-20 16:14 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +        LOG(WARNING) << "duplicate Nat Stat counter dyn gauge family"
shift right to align with the g above

2024-02-20 16:14 UTC, mchalla commented on agent-ovs/lib/AgentPrometheusManager.cpp
> +    return false;
add space here

2024-02-21 19:38 UTC, merged